### ISSUE TITLE
curly braces not recognized (indent)

### ISSUE THREAD

**Issue by davidmathei** [xquery-mode/xquery-mode#14]
```xquery

declare function local:test-level-transmission($file-data as node(),$inbound-test-file-uri as xs:string) as node()
{ (: carries both previous-icn /next pointers:)
let $enc := $file-data/env:source/enc-xml:test
let $env := $file-data/env:metadata
return <test-transmission xmlns="https://some.ns" processing-method="test-level">
         <icn>{local:icns(1)}</icn>
         <remote-icn />
           <plan>{$env/env:plan/text()}</plan>
           <!-- FIXME this would mandate explicit element constructors -->
           <frequency>{if ($enc/enc-xml:voided)
                       then "void"
                       else ()}</frequency>
           <ids>
             {
               for $pci in $env/env:ids/env:id/text()
               return <id>{$pci}</id>
             }
           </ids>
           <data />
             <test-data>{xdmp:node-uri($file-data)}</test-data>
             <generation>{$enc/enc-xml:generation/text()}</generation>
             <status>
               <code>pending</code>
               <timestamp>{$now}</timestamp>
               <cause>{$inbound-test-file-uri}</cause>
             </status>
             <status-history />
       </test-transmission>
};
```

**Comment by proofit404** [comment]
Hi @davidmathei 

I've tried all examples submitted in the #11, #12, #13 and #14. They work out of the box on my machine. Passed tests on Travis-CI says the same.

It looks like we setup wrong version of the xquery-mode on your server, sorry. Please try to install it from the master branch of this repository. Maybe even copy-pasting from github page to be sure.

If error will still persist after this changes, please submit verbose report of your environment. For example full emacs version, current git commit of the xquery-mode repository and full buffer content.

Regards, Artem.

**Comment by davidmathei** [comment]
Thank you @proofit404 ! Turns out that we had setup xquery-mode correctly,  but per .emacs xdbc-selector was used with still an old submodule. I tested the four issues and see that xquery-moe works for me (upgraded to oook-selector with the current xquery-mode version) 

Regards & thanks again,

David

**Comment by proofit404** [comment]
Glad it works.
