### ISSUE TITLE
Define comment syntax

### ISSUE THREAD

**Issue by hlolli** [xquery-mode/xquery-mode#15]
I see this as a low hanging fruit but by defnining comment syntax for this major mode, its possible to easily access block comment functions like `comment-or-uncomment-region` which needs to have pre-defined comment syntax. A stackoverflow user explains this here btw http://stackoverflow.com/questions/25400328/how-can-i-define-comment-syntax-for-a-major-mode/25556594#25556594

**Comment by proofit404** [comment]
Done. Please give it a try.

Regards, Artem.

**Comment by hlolli** [comment]
Works, looks weird with multiline commenting due to the weirdness of xquery comment syntax.

example:

```
(: 
 : I
 : am
 : a
 : multiline
 : comment
 :)
```

but only posting this for the laughs.
